services:
  book_service:
    build:
      context: book
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  review_service:
    build:
      context: reviews
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - book_service
      - review_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
